### ISSUE TITLE
About and Support no longer hidden after recent update.

### ISSUE THREAD

**Issue by zanderzhng** [denis-g/userstyle-simply-steam-ui#2]
Not sure which update, but they look like this now.
<img width="715" alt="screen shot 2016-05-26 at 7 23 04" src="https://cloud.githubusercontent.com/assets/867749/15559221/d58a3bba-2312-11e6-85f4-5db25b48bdaf.png">

The _display:none_ is not working.

Safari with Stylish Extension.

**Comment by denis-g** [comment]
Yes, this is [bug](https://github.com/350d/stylish/issues/14) Stylish for Safari.
Latest update fixed this bug.

**Comment by zanderzhng** [comment]
lol what a small world I saw the stylish issue days ago but I didn't realized it's talking about this style.
btw fix confirmed thank you.
