### ISSUE TITLE
Well you fixed the feature that hide asian languages away.

### ISSUE THREAD

**Issue by zanderzhng** [denis-g/userstyle-simply-steam-ui#3]
May you bring these language back?
It's not hard to edit the style in extension though but may be not that kind to Asians, like me.
I'm writing a post to recommend customizations like air theme and styles for steam, and it would be much easier if you bring these languages back so I don't have to do a fork or a guide to edit style.

**Comment by denis-g** [comment]
Yep, in next version i'm created new design for languages menu and showed all lang items. To be updated soon.

**Comment by denis-g** [comment]
Updated.
