### ISSUE TITLE
No Steam logo in the Header

### ISSUE THREAD

**Issue by eti0** [denis-g/userstyle-simply-steam-ui#4]
Hey, so as the title says there's no Steam logo in the header, I wonder if this theme gets updates or no, anyway I hope you can fix this.
If you don't get this issue you might wanna look at my screenshot of the issue.

![no-logo](https://cloud.githubusercontent.com/assets/14180792/15993486/47eed44e-30e8-11e6-9c68-75796a87cb8d.png)

Thanks.

**Comment by denis-g** [comment]
Fixed.
