### ISSUE TITLE
[Bug & Suggestions] Profile issue & dark theme and enhanced steam button?

### ISSUE THREAD

**Issue by JourneyOver** [denis-g/userstyle-simply-steam-ui#5]
Well for the bug first -- 
recent update seems to have shifted a section of the profile page to the left -- http://i.imgur.com/mHKAJRo.png think the issue could be because of the steamdb button being so huge on own profile, going to someone else's profile the layout of the profile page is correct http://i.imgur.com/FzP5wkv.png.

suggestions -- 
1. Blue theme that steam has going on is just kinda bleh always has been, so would like to maybe see a dark theme of this. Right now I'm running the dark theme from here https://userstyles.org/styles/105705/raydell-s-dark-steam-ui-theme-only alongside flat steam UI but there are a few coloring issues between using both the flat steam UI and the dark steam UI from above.
2. Add a button on the header somewhere for the enhanced steam dropdown menu as currently there is no button for it while using this theme even though you say you have enhanced steam support.

**Comment by denis-g** [comment]
Hi @JourneyOver, thanks for comment.
How you added SteamDB button in profile page?

And:
1. The third-party themes support is not planned, but I'll see what I can do.
2. Yep, this button hidden because there is no place for it. Maybe something good will come out...

**Comment by JourneyOver** [comment]
It's from the steam database extension located here -- [SteamDB Extension](https://chrome.google.com/webstore/detail/steam-database/kdbmhfkmnlmbkgbabkdealhhbfhlmmon?utm_source=chrome-app-launcher-info-dialog). there was no issues before the latest update to the style, but after the latest update to the style the button ended up becoming huge and making half the profile page shift left. Disabling the style and/or disabling the extension causes the profile to be corrected.
1. That's fine, just would be nice to see darker colors for the style.
2. can you at least create a small "ES" icon under the mail icon that'll do the dropdown maybe so it's easier to go into the enhanced steam options? as currently the only way to get into the options for enhanced steam is to disable to the style and then go into the options and re-enable the style, and you have to keep doing this any time you want/have to go into the options for whatever reason.
