### ISSUE TITLE
How to apply on my steam client?

### ISSUE THREAD

**Issue by Conoi1** [denis-g/userstyle-simply-steam-ui#6]
Hello how are you?

Man I really want add that style to steam client, had changed on my browser and saw badges page, also like it to much!

Can you help me please?

Thanks 💯/ 💯 

CONOI

**Comment by denis-g** [comment]
This is works only with proxy, example _Enhanced Steam Standalone_ [(development stopped)](http://www.enhancedsteam.com/blog/enhanced-steam-standalone-project-discontinued/). Currently this is not possible.

**Comment by Conoi1** [comment]
Ok thank you!
