### ISSUE TITLE
Game bans are not visible on private profiles

### ISSUE THREAD

**Issue by mellowagain** [denis-g/userstyle-simply-steam-ui#7]
With theme:
![With theme](https://i.gyazo.com/71a4d0a9017885a73af71d35d3138bbe.png)

Without theme:
![Without theme](https://i.gyazo.com/de87b4136d0eec5a26c316a39820e4ad.png)

They are visible on public profiles, but on private there are not when using this theme.

**Comment by denis-g** [comment]
Thanx & update! 👍
